=== vqthang3791/SEM_2/XML/Lab2/EventManagement_schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema targetNamespace="http://www.creativemanagement.com"
           xmlns="http://www.creativemanagement.com"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Customer" type="xs:string"/>
    <xs:element name="Venue" type="xs:string"/>
    <xs:element name="Date" type="xs:date"/>
    <xs:element name="ContractNumber" type="xs:long"/>
    <xs:element name="Address" type="xs:string"/>
    <xs:element name="TechDelivery" type="xs:string"/>
    <xs:element name="Entertainment" type="xs:string"/>
    <xs:element name="VenueBooking" type="xs:string"/>
    <xs:element name="Themeing" type="xs:string"/>

    <!--definition for simple types-->
    <xs:element name="NoOfGuests">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="0"/>
                <xs:maxInclusive value="2000"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <!--definition for complex elements-->
    <xs:element name="Event">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Customer"/>
                <xs:element ref="Venue"/>
                <xs:element ref="Date"/>
                <xs:element ref="NoOfGuests"/>
                <xs:element ref="ContractNumber"/>
                <xs:element ref="Address"/>
            </xs:sequence>
            <xs:attribute name="orderid" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Service">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="TechDelivery"/>
                <xs:element ref="Entertainment"/>
                <xs:element ref="VenueBooking"/>
                <xs:element ref="Themeing"/>
            </xs:sequence>
            <xs:attribute name="category" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="EventManager">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Event" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="Service" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== vqthang3791/SEM_2/XML/Lab2/EventManagement.xml
<?xml version="1.0" encoding="UTF-8" ?>

<EventManager xmlns="http://www.creativemanagement.com"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.creativemanagement.com EventManagement_schema.xsd">
    <Event orderid ="A556">
        <Customer>TideWaterHouseCoopers</Customer>
        <Venue>Hilton Bermingham Metropole</Venue>
        <Date>2007-04-24</Date>
        <NoOfGuests>500</NoOfGuests>
        <ContractNumber>3453667</ContractNumber>
        <Address>32 High Street, North Midlands</Address>
    </Event>

    <Service category="AnnualConference">
        <TechDelivery>Multimedia Arrangement</TechDelivery>
        <Entertainment>Media Personality</Entertainment>
        <VenueBooking>Through TravelDesignated </VenueBooking>
        <Themeing>Emulate Movie Themed Dinner</Themeing>
    </Service>
</EventManager>
